# Generated by Django 4.1 on 2022-09-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='userid',
            new_name='Userid',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='username',
            new_name='Username',
        ),
        migrations.AddField(
            model_name='details',
            name='Count',
            field=models.IntegerField(default=0),
        ),
    ]
