# Generated by Django 4.1 on 2022-09-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0002_rename_userid_details_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Count',
            new_name='Counter',
        ),
    ]
